version: "3.9"

services:
  db:
    image: postgres:13
    ports:
      - 32700:5430
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres