con = psycopg2.connect(
        database="postgres",
        user="postgres",
        password="postgres",
        host="127.0.0.1",
        port="5433"
    )

    print("Database opened successfully")

    cur = con.cursor()
    # cur.execute('''ALTER TABLE example_table ALTER COLUMN
    #      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    #      ''')

    # print("Table created successfully")
    # con.commit()
    # con.close()

    # try:


# img2 = io.imread(path_to_photos + '/' + faces[distances.index(min_dist)])
    #
    # if min_dist > 0.6 and len(face_descriptors) == 1:
    #     print('На фотографиях разные люди!')
    # elif min_dist <= 0.6 and len(face_descriptors) > 1:
    #     print('Полученное лицо совпадает с лицом на фото ' + faces[distances.index(min_dist)])
    #     plt.figure(figsize=(10, 6))
    #     plt.subplot(1, 2, 1)
    #     plt.title(f"Полученное лицо:")
    #     plt.imshow(img)
    #     plt.subplot(1, 2, 2)
    #     plt.title("Предполагаемый человек:")
    #     plt.imshow(img2)
    #     plt.show()
    # elif min_dist > 0.6 and len(face_descriptors) > 1:
    #     print('Точно сказать не могу, но наверное это человек с фотографии ' + faces[distances.index(min_dist)])
    #     plt.figure(figsize=(10, 6))
    #     plt.subplot(1, 2, 1)
    #     plt.title(f"Полученное лицо:")
    #     plt.imshow(img)
    #     plt.subplot(1, 2, 2)
    #     plt.title("Предполагаемый человек:")
    #     plt.imshow(img2img2)
    #     plt.show()